In [ ]:
from array import *
array_num = array('i', [1, 3, 5, 3, 7, 1, 9, 3])
print("Original array: "+str(array_num))
num_list = array_num.tolist()
print("Convert the said array to an ordinary list with the same items:")
print(num_list)

Original array: array('i', [1, 3, 5, 3, 7, 1, 9, 3])
Convert the said array to an ordinary list with the same items:
[1, 3, 5, 3, 7, 1, 9, 3]


In [ ]:
import numpy as np
  
n_array = np.array([[55, 25, 15],
                    [30, 44, 2],
                    [11, 45, 77]])
  
print("Numpy Matrix is:")
print(n_array)

trace = np.trace(n_array)
  
  
print("\nTrace of given 3X3 matrix:")
print(trace)

Numpy Matrix is:
[[55 25 15]
 [30 44  2]
 [11 45 77]]

Trace of given 3X3 matrix:
176


In [ ]:
import numpy as np
x = np.array([[0, 10, 20], [20, 30, 40]])
print("Original array: ")
print(x)
print("Values bigger than 10 =", x[x>10])
print("Their indices are ", np.nonzero(x > 10))


Original array: 
[[ 0 10 20]
 [20 30 40]]
Values bigger than 10 = [20 20 30 40]
Their indices are  (array([0, 1, 1, 1]), array([2, 0, 1, 2]))


In [18]:
a =np.random.randint(2, 10, size=(2,4))
b=np.random.randint(7, 19, size=(2,4))
print(a)

print(b)
c = np.add(a, b)
print(c)

[[4 9 9 3]
 [8 4 5 6]]
[[17  9 16 16]
 [ 9 10 18  8]]
[[21 18 25 19]
 [17 14 23 14]]


In [47]:
a = np.random.randint(2, 10, size=(2,4))
b= np.mean(a,axis =1)
print(a)
print(b)
Liste = b.tolist()
print(f'List:{Liste}')
index = 0
for i in a :
  index2 =0
  for j in i:
    a[index,index2] -= round(Liste[index])
    index2 += 1
  index += 1
print(a)



[[6 9 8 9]
 [9 6 7 8]]
[8.  7.5]
List:[8.0, 7.5]
[[-2  1  0  1]
 [ 1 -2 -1  0]]


In [29]:
import numpy as np
print("Original matrix:\n")
X = np.random.randint(2, 10, size =(2,19))
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X.mean(axis=1, keepdims=True)
print(Y)


Original matrix:

[[5 8 2 9 8 6 8 6 4 6 6 5 2 9 3 6 5 5 3]
 [6 2 3 7 9 9 8 5 6 2 4 7 7 3 5 2 8 8 3]]

Subtract the mean of each row of the said matrix:

[[5.57894737]
 [5.47368421]]
